server:
  port: 8084
  error:
    include-message: always

spring:
  application:
    name: ms-payment

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/db_payment
    username: <user>
    password: <password>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

